# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    #app.command.crawl_japscan:
    #    class: AppBundle\Command\CrawlJapscanCommand
    #    tags:
    #        - { name: console.command }